### ISSUE TITLE
add "storage gateway" extension to blockstored API?

### ISSUE THREAD

**Issue by peacekeeper** [blockstack/blockstack-server#133]
I understand blockstore-cli talks to blockstored only for blockchain-related operations, but as for the actual data storage (DHT, etc.), blockstore-cli accesses the storage directly. There are good reasons for this, i.e. users are in control where the data is stored.

I'm trying to work on a Java client for blockstore:
https://github.com/projectdanube/blockstore-cli-java

And it seems it could be useful if blockstored could also expose all storage-related operations (in addition to the blockchain-related operations). This way, new client libraries would be much easier to write, since they only have to deal with JSON-RPC calls.

I understand to accomplish this, a blockstored extension could "wrap a server-side copy of the client library"?

(This issue is based on a Slack conversation with muneeb_onename and jude_onename).

**Comment by jcnelson** [comment]
Note to self: consider re-purposing blockmirrord.py for this purpose.

**Comment by jcnelson** [comment]
This has been added, and is tested and used in the new stable release.  To use it, set `serve_zonefiles = True` and `serve_profiles = True` in the `[blockstack-server]` section of your Blockstack server's config file.  You can further control which storage drivers to use with the `zonefile_storage_drivers` and `profile_storage_drivers`.

In the client, you should enable `blockstack_server` as one of the storage drivers to use.  This will cause the client to replicate its zonefiles and profiles to the Blockstack server.
