### ISSUE TITLE
Pending to-dos

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-server#151]
Moving over some items from Trello, as we are no longer going to use Trello. These can be converted into separate issues and/or deleted from here:

* Find strategy for preventing targeted denials of service against DHT.
* Build sample application: public-key repository and daemon for setting up SSH for your VMs.
* Syndicate command-line tools
* Add support for building Syndicate with the native client toolchain.
* Syndicate black-box tests.
* Blockstore health-check instrumentation

**Comment by muneeb-ali** [comment]
@jcnelson A bunch of these are Syndicate-related and can be moved to Syndicate's repo?

**Comment by jcnelson** [comment]
Yeah, I'll take the Syndicate ones.  No need to track them here.

**Comment by shea256** [comment]
I read this as "pending to DOS" and got a bit freaked out for a hot second ha.

**Comment by jcnelson** [comment]
Closing this and re-opening as #226, #227, #228
