### ISSUE TITLE
update the values of the output format for the lookup command

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-server#158]
Earlier we discussed changing the names of the address, script, public key, etc. to make sure they all have the "owner" prefix to make it clear that they all pertain to the owner. "owner" is also a more appropriate term than "sender" which is really ambiguous.

At this point, I'm suggesting we update the values of the lookup response to the following:

```json
[
    {
        "owner_address": "19MoWG8u88L6t766j7Vne21Mg4wHsCQ7vk",
        "owner_script": "76a9145bb0253ff5a02082942615d3d215079e9c5bdb9f88ac",
        "owner_public_key": "03a75eab0d1e1e7e71a237c5580c4ff060d6033391ab7cbd9e3cf881f41633a68b",
        "first_registered": 374085,
        "last_renewed": 374085,
        "revoked": false,
        "value_hash": "c9efe60e0eca3802777a8accee4e38ded8422891"
    }
]
```

**Comment by jcnelson** [comment]
This has been significantly overhauled :)
