### ISSUE TITLE
add type-checking rules to the RPC interface

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-server#192]
For example, the register call should check if the owner_address was a valid bitcoin address (and not something else), currently we get 

> utilitybelt/charsets.py\", line 34, in charset_to_int",
        "    output = output * len(charset) + charset.index(char)",
        "ValueError: substring not found"

for this particular case.

There might be other checks that'd be needed.

**Comment by jcnelson** [comment]
Also, check testnet vs mainnet addresses.

**Comment by jcnelson** [comment]
This is added in the new stable release.
