### ISSUE TITLE
Update generates transaction even when inadequate bitcoin

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-server#194]
Blockstore doesn't tell the user there's not enough bitcoin to complete an `update` operation and instead generates a transaction that cannot be broadcast.

For example: 

running
`blockstore-cli update theblockchain.id "$(cat ~/theblockchain.json)" "$(cat ~/theblockchain.key)"`

at block time ~385,370

where `theblockchain.key` is the private key for 17iU96GDj4E7KoBLVr4YnvN3QMfZuYWT5K

```
{
    "error": "Exception: Tx hash missing from blockcypher response: {u'error': u'Error sending transaction: Transaction ab9d961bc1c4cd7e2eb5afc4d80b8bfdb32012a1cfb45a54143325c55bf5ca95 non standard: dust.'}",
    "traceback": [
        "Traceback (most recent call last):",
        "  File \"/srv/blockstore-venv/local/lib/python2.7/site-packages/blockstore/blockstored.py\", line 587, in blockstore_name_update",
        "    tx_only=tx_only, blockchain_broadcaster=broadcaster_client_inst, user_public_key=user_public_key, testset=blockstore_opts['testset'])",
        "  File \"/srv/blockstore-venv/local/lib/python2.7/site-packages/blockstore/lib/operations/update.py\", line 177, in broadcast",
        "    response = broadcast_transaction( signed_tx, blockchain_broadcaster )",
        "  File \"/usr/local/lib/python2.7/dist-packages/pybitcoin/transactions/network.py\", line 51, in broadcast_transaction",
        "    return blockcypher.broadcast_transaction(hex_tx, blockchain_client)",
        "  File \"/usr/local/lib/python2.7/dist-packages/pybitcoin/services/blockcypher.py\", line 89, in broadcast_transaction",
        "    raise Exception(err_str)",
        "Exception: Tx hash missing from blockcypher response: {u'error': u'Error sending transaction: Transaction ab9d961bc1c4cd7e2eb5afc4d80b8bfdb32012a1cfb45a54143325c55bf5ca95 non standard: dust.'}"
    ]
}
```

<img width="601" alt="screen shot 2015-11-26 at 1 35 30 pm" src="https://cloud.githubusercontent.com/assets/597182/11415943/ff142292-9443-11e5-9718-3a811113ef9a.png">

By sending additional bitcoin to 17iU96GDj4E7KoBLVr4YnvN3QMfZuYWT5K (https://live.blockcypher.com/btc/tx/ac1b21323027a2c093f796f7c6572b68ee4d52fd805dd9d8ac24b8f090e3edf0/) and running `update` again, the resulting transaction was able to be broadcast: https://live.blockcypher.com/btc/tx/91cb40ea52ded01b3de02a9fb385231e815f0c955c7735a404b00219005b9792/

**Comment by jcnelson** [comment]
This should no longer be happening in the new stable client.  Please re-open if you see this again :)
