### ISSUE TITLE
suggested feature: add a delete operation

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-server#199]
After reflecting more on the core operations that Blockstore provides, I've come to the conclusion that we will need a delete operation.

The reason is that you may not want to have certain names anymore. Certain names may be repulsive or unwanted, and while you could send them to the null address, that's a bit of a hack, as well as problematic since each address can only hold 25 names. Address deletion also signifies the right thing - that you are done using the identity and that it should be removed from listing.

Thoughts?

**Comment by jcnelson** [comment]
We solved this with `revoke`.
