### ISSUE TITLE
'rollback' command for blockstored

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-server#205]
It'd be nice to have a 'rollback' command for blockstored where you can rollback the DB to a previous block. 

The use case for this is that let's say you detect that you're on a fork (for whatever reason, say software error) and you don't want to reprocess all blocks from blockstore's genesis block. 

Seems like the functionality is already there and we need to automate it a bit. Here is a response from @jcnelson:

> the necessary code to do a "rollback" like you described is there, but there's not an overarching command to do it.  You can use the `verifydb` command to process a db from the beginning up to a given consensus hash, and then use the resulting db directory (saved to a temporary directory) as your canonical db.  It's not that efficient for going back only a few blocks, but it would work for now. (I'd have to write the code to go "backwards" from the present db to a prior version, but I'm sure it's possible since we store sufficient information to do so)

**Comment by jcnelson** [comment]
The server is configured to make backups periodically, and now offers a `restore` command to revert the database from a backup.
