### ISSUE TITLE
Support Date/Time Formatting in Logging

### ISSUE THREAD

**Issue by doodlemania2** [blockstack/blockstack-server#224]
could we add something like this to blockstackd.py?
logging.basicConfig(format='%(asctime)s %(message)s', datefmt='%m/%d/%Y %I:%M:%S %p')

line 45 says to use virtualchain's session log (I think) which follows back to session.py in blockstack-virtualchain right around line 62 which has some formatting but not sure if that's where this should go

basically, would be good to see the date/timestamp on all server logging

**Comment by jcnelson** [comment]
Sure, we can add that

**Comment by jcnelson** [comment]
Added via virtualchain.  Should be present in the stable release.
