### ISSUE TITLE
add in support for name admins

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-server#28]

**Comment by jcnelson** [comment]
I'm not sure what this means.  Can you elaborate?

**Comment by shea256** [comment]
The idea would be to give different keys different permissions related to the name.

| Role         | Renew?   | Update?    | Transfer? |
| ------------- |:-------------:|:-------------:|:-------------:| 
| Owner      | YES         | YES          | YES         |
| Admin      | YES         | YES          | NO           |
| Renewer  | YES         | NO            | NO           |

**Comment by jcnelson** [comment]
Sounds reasonable--we could give each principal an HD key pair derived from the owner's key pair, and add an operation (let's call it NAME_DELEGATE) that declares that a derived public key has the "admin" or "renew" capabilities for the name.

**Comment by shea256** [comment]
Cool, but I don't think it should be defined as or restricted to a keychain derived from the owner. I would imagine that renewers would be services like onename, and admins could be client software that's different from the owner client software.

**Comment by jcnelson** [comment]
I'm guessing you're envisioning a way for NAME_DELEGATE to provide the blockchain ID of the service that has the given role?

**Comment by shea256** [comment]
Yes, exactly.

**Comment by jcnelson** [comment]
Sounds good; will implement that.
