### ISSUE TITLE
improve system for setting bitcoind configs

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-server#74]
I suggest we do the following:

1. check the bitcoin.conf file for config info
1. add a call for re-inputting the config info
1. stop prompting the user to re-input the config info upon the starting of bitcoind and failure to connect (the former makes this make even more sense)

**Comment by jcnelson** [comment]
(3) is done.  I can add (1) and (2).

**Comment by shea256** [comment]
:+1:

**Comment by jcnelson** [comment]
(2) is done, and we just choose sensible defaults if no input is given.
